=  CHANGELOG
Shulhan <ms@kilabit.info>
:toc:
:sectanchors:
:sectlinks:

This library is released every month, usually at the first week of month.

link:CHANGELOG_2022.html[Changelog in 2022^].
This is changelog for share module since v0.33.0 until v0.42.0.

link:CHANGELOG_2021.html[Changelog in 2021^].
This is changelog for share module since v0.22.0 until v0.32.0.

link:CHANGELOG_2020.html[Changelog in 2020^].
This is changelog for share module since v0.12.0 until v0.21.0.

link:CHANGELOG_2018-2019.html[Changelog from 2018 to 2019^].
This is changelog for share module since v0.1.0 until v0.11.0.


[#v0_45_0]
==  share v0.45.0-dev (2023-04-xx)

[#v0_45_0__new_features]
===  New features

lib/http: add function to parse multipart Range response for Client::
+
The ParseMultipartRange parse the multipart/byteranges body or response
from HTTP Range request.
Each Content-Range position and body part in the multipart will be stored
under RangePosition.

lib/http: add support for HTTP Range in Server::
+
--
For HTTP Server using HandleFS, the Range request is handled
automatically.
For other HTTP server, user can use the HandleRange function.

The HandleRange function handle [HTTP Range] request using "bytes" unit.
The body parameter contains the content of resource being requested that
accept Seek method.

If the Request method is not GET, or no Range in header request it will
return all the body [RFC7233 S-3.1].

The contentType is optional, if its empty, it will detected by
http.ResponseWriter during Write.

[HTTP Range]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests
[RFC7233 S-3.1]: https://datatracker.ietf.org/doc/html/rfc7233#section-3.1
--

lib/parser: add method TokenTrimSpace::
+
The TokenTrimSpace read the next token until one of the delimiter found,
with leading and trailing spaces are ignored.

lib/parser: add method SetDelimiters::
+
The SetDelimiters replace the current delimiters.

[#v0_45_0__enhancements]
===  Enhancements

lib/test: simplify the string diff output from Assert::
+
--
In the output, instead of using %q we replace it with %s, because printing
string with double quote cause escaping and hard to read
This change may cause difference in white spaces not showed in the
terminal.

In the diff changes, only print the Old and New, without printing each
chunk.
--


[#v0_44_0]
==  share v0.44.0 (2023-03-02)

[#v0_44_0__new_features]
===  New features

lib/time: implement Scheduler::
+
--
Scheduler is a timer that run periodically based on calendar or day time.

A schedule is divided into monthly, weekly, daily, hourly, and minutely.
An empty schedule is equal to minutely, a schedule that run every minute.
--

lib/time: add new type Clock::
+
Clock represent 24 hours time with hour, minute, and second.
An hour value is from 0 to 23, a minute value is from 0 to 59, and
a second value is from 0 to 59.

[#v0_44_0__bug_fixes]
===  Bug fixes

lib/clise: fix potential data race between Push and Slice::
+
The data race may occur if Push is called, the .last field is incremented
and at the same time an other goroutine call Slice that access the .last
field.

lib/memfs: minimize data race on DirWatcher::
+
Calling DirWatcher Stop while the start method set dw.ticker can cause
data race.  This changes fix this issue.

go.mod: update all dependencies::
+
This update use "go get all" which resolve to semver for each dependencies.

[#v0_44_0__chores]
=== Chores

all: set the test timeout to 1m::
+
Some flaky test, caused by waiting for channel, require waiting for 10m
before it considered fail.
This changes we cut the default timeout to 1 minute.

all: access embedded field or methods using the type name::
+
This is for clarity in the code, better to be explicit by typing where
the field or methods come from.

lib/email: add an example for Filter method on Header::

cmd: temporarily hide unused commands::
+
The cart, cascaded-random-forest, lnsmote, random-forest, and smote
are part of completing thesis and they never used anymore.

AUR: add go-test-coverhtml.sh and go-bench.sh into package::
+
While at it, changes the go-bench count to 10.

lib/websocket: replace math/rand.Read with crypto/rand.Read::
+
The math/rand will be deprecated in Go 1.20.


[#v0_43_0]
==  share v0.43.0 (2023-02-07)

[#v0_43_0__new_features]
===  New features

lib/http: add function MarshalForm::
+
--
The MarshalForm marshal struct fields tagged with `form:` into url.Values.

The rules for marshaling follow the same rules as in [UnmarshalForm].

It will return an error if the input is not pointer to or a struct.
--

clise: implement io Closer, Writer, StringWriter, and ByteWriter::

clise: add method UnmarshalJSON::
+
The UnmarshalJSON convert JSON array into Clise.
