= CHANGELOG
:toc:
:sectanchors:

This library is released every month, usually at the first week of month.

link:CHANGELOG_2023.html[Changelog in 2023^].
This is changelog for share module since v0.43.0 until v0.51.0.

link:CHANGELOG_2022.html[Changelog in 2022^].
This is changelog for share module since v0.33.0 until v0.42.0.

link:CHANGELOG_2021.html[Changelog in 2021^].
This is changelog for share module since v0.22.0 until v0.32.0.

link:CHANGELOG_2020.html[Changelog in 2020^].
This is changelog for share module since v0.12.0 until v0.21.0.

link:CHANGELOG_2018-2019.html[Changelog from 2018 to 2019^].
This is changelog for share module since v0.1.0 until v0.11.0.

[#v0_52_0]
== share v0.52.0 (2024-01-06)

[#v0_52_0__new_features]
===  New features

ssh/config: add method MarshalText and WriteTo::
+
--
The MarshalText method encode the Section back to ssh_config format
with two spaces as indentation in key.

The WriteTo method marshal the Section into text and write it to
[io.Writer] w.
--

lib/ssh: implement method Output on Client::
+
--
The Output method run the command and return its standard output and
error as is.
Any other error beside standard error, like connection, will be returned
as error.
--

ssh/sftp: implement method MkdirAll on Client::
+
--
The MkdirAll create directory on the server, from left to right.
Each directory is separated by '/', where the left part is the parent of
the right part.
This method is similar to [os.MkdirAll].
--

cmd/httpdfs: implement [libhttp.Server] with [memfs.MemFS]::
+
--
The httpdfs is a program to serve a directory under HTTP.
--

[#v0_52_0__breaking_changes]
=== Breaking changes

ssh/config: refactoring the Config merge::
+
--
This changes rename method [Config.Prepend] to [Config.Merge].

The way that how the other Config merged is changed.
Instead of appending all of other's sections into the current Config,
append the other Config instance to the current instance of Config.

During [Config.Get] the top Config will be evaluated first, and then the
other Config is evaluated in order of Merge.
--

ssh/config: add parameter Config to NewSection::
+
--
This changes how the Section and parser initialized.

Previously, the Config depends on the parser to set the workDir and
homeDir and Section depends on Config only on Get; now its the other
way around, from top to bottom.
Config initialized first, then parser initialized using Config instance,
and then Section initialized also using Config instance.
--

lib/ssh: add parameter context to Execute method::
+
--
This changes require the fork of our golang.org/x/crypto.
--

lib/time: remove UnixMicro and UnixMilli::
+
--
Both of those methods has been added into standard library as
[Time.UnixMicro] and [Time.UnixMilli] since Go 1.17.
--

lib/io: removed, this package has been merged into "lib/os"::
+
--
While some functions are merged to "lib/os", some are not used anymore
like io.Reader.
--

lib/parser: removed, this package has been merged into lib/strings::


[#v0_52_0__bug_fixes]
=== Bug fixes

ssh/config: fix setting the default values::
+
--
The field default value should be set on Get, after all the Host or
Match fields merged.
In this way, if the field key already set, its not overridden by the
default value or subsequent Host or Match value.
--

ssh/config: set the Hostname if its not set on [Config.Get]::
+
--
Per manual ssh_config(5) on Hostname,

[quote]
The default is the name given on the command line.

So, if the requested host name match with one of Host or Match, but
Hostname is not set, it should be default to the requested parameter
name.
--

http/sseclient: fix data race on [Client.Close]::
+
--
The data race happened when Close set conn to nil but the consume
method still on Read.
The fix is by waiting for 100ms so consume goroutine can check if closeq
is triggered from Close or not.
--

http/sseclient: fix Retry value not set to millisecond::
+
--
When client receive "retry:" message, the value is in millisecond, but
when we store it we only convert it to [time.Duration] which default
to nanosecond.

While at it, update comments on field [Client.Retry] and
[Client.Insecure].
--

ssh/sftp: fix Stat on empty remote file name::
+
--
The implementation of SSH server (openssh) for Stat is not consistent with
the RFC.
The RFC mentioned that

[quote]
An empty path name is valid, and it refers to the user's default
directory (usually the user's home directory).

But this only working on some command, like Mkdir, but not Stat.
--

ssh/sftp: fix non-nil returned error on Close::
+
--
This changes fix the Close that always return an error.
--


[#v0_52_0__enhancements]
===  Enhancements

ssh/config: merge the Section slice values on [Section.merge]::
+
--
Instead of using [Section.Set], set the key-value directly.

While at it, merge the certificateFile, IdentityFile, knownHostFiles,
and sendEnv.
--

ssh/config: set the default UserKnownHostsFile in setDefaults::
+
--
While at it, unfold each value of IdentityFile and UserKnownHostsFile
in setDefaults, by expanding "~" into user's home directory or joining
with "config" directory if its relative.
--
