= CHANGELOG
:toc:

This library is released each month, either at the end of month or at the
first week of next month.

== share v0.3.0 (2019-xx-xx)

=== New Features

* `lib/debug`: add type to store relative and difference on memory heap
* `lib/dns`: add type of connection
* `lib/http`: add parameter http.ResponseWriter to Callback.
* `lib/http`: the RegisterXxx functions now use the Endpoint type.


== share v0.2.0 (2019-01-02)

=== New Features

* `lib/errors`, package errors provide a custom error with code.

* `lib/http`, package http implement custom HTTP server with memory file
system and simplified routing handler.

=== Enhancements

Fix warnings from linters.


== share v0.1.0 (2018-11-29)

The first release of `share` package contains one command line interface (CLI)
and several libraries.

The CLI is `gofmtcomment` to convert comment from `/**/` to `//`.

The libraries are `bytes`, `contact`, `dns`, `dsv`, `ini`, `io`, `memfs`,
`mining`, `net`, `numbers`, `runes`, `strings`, `tabula`, `test`, `text`,
`time`, and `websocket`.

Documentation for each package can be viewed at,

	https://godoc.org/github.com/shuLhan/share

I hope it will be stay alive!
