= CHANGELOG
:toc:
:sectanchors:

This library is released every month, usually at the first week of month.

link:CHANGELOG_2023.html[Changelog in 2023^].
This is changelog for `pakakeh.go` module since v0.43.0 until v0.51.0.

link:CHANGELOG_2022.html[Changelog in 2022^].
This is changelog for `pakakeh.go` module since v0.33.0 until v0.42.0.

link:CHANGELOG_2021.html[Changelog in 2021^].
This is changelog for `pakakeh.go` module since v0.22.0 until v0.32.0.

link:CHANGELOG_2020.html[Changelog in 2020^].
This is changelog for `pakakeh.go` module since v0.12.0 until v0.21.0.

link:CHANGELOG_2018-2019.html[Changelog from 2018 to 2019^].
This is changelog for `pakakeh.go` module since v0.1.0 until v0.11.0.


[#v0_53_1]
== pakakeh.go v0.53.1 (2024-03-02)

[#v0_53_1__enhancements]
=== Enhancements

lib/sql: handle binding with the same name::
+
If [Meta.Bind] is called with the same name again, it should replace
the existing named value.


lib/dns: ignore invalid message::
+
--
If Query return a message but the failed to unpack due to invalid
format, for example

      unpackOPT: data length is out of range

ignore it instead of disconnect the client connection.
--


lib/http: export function to generate "multipart/form-data"::
+
The GenerateFormData generate the request body with boundary for
HTTP content-type "multipart/form-data" from map[string][]byte.


lib/dns: change the log mechanism by mode instead of by level::
+
--
This changes introduce three mode of debug:

* DebugLevelDNS: log error on DNS level, in example empty answer,
  ERR_NAME (domain name is invalid or not known) and so on.

* DebugLevelCache: log cache operations.

* DebugLevelConnPacket: log low level connection and package,
  including request and response.
--


[#v0_53_0]
== pakakeh.go v0.53.0 (2024-02-04)

[#v0_53_0__new_features]
===  New features

test/mock: implement mock for crypto [rand.Reader]::
+
--
The RandReader implement [io.Reader].
To provide predictable result, the RandReader is seeded with slice of
bytes.
A call to Read will fill the passed bytes with those seed.

For example, given seed as "abc" (length is three), calling Read with
bytes length five will return "abcab".
--


lib/sql: add new type Meta::
+
--
Meta contains the DML meta data, including driver name, list of column
names, list of column holders, and list of values.

The Meta type replace the Row type.
--


lib/path: new package to work with path::
+
--
The path package provide a new type Route, detached from "lib/http".

A Route represent a parsed path.
A path can have a key, or binding, that can be replaced with string
value.
For example, "/org/:user/:repo" have two keys "user" and "repo".

Route handle the path in case-insensitive manner.
--


[#v0_53_0__bug_fixes]
===  Bug fixes

_bin/go-mod-tip: use committer timestamp instead of author timestamp::
+
If the tip is rebased to upstream, the author timestamp is not changes,
but the commit timestamp changes.


[#v0_53_0__enhancements]
===  Enhancements

lib/totp: add method GenerateWithTime and GenerateNWithTime::
+
The GenerateWithTime and GenerateNWithTime accept parameter
[time.Time] as the relative time for generated password.


lib/http: add support for If-Modified-Since in HandleFS::
+
If the node modification time is less than requested time value in
request header If-Modified-Since, server will response with
304 Not Modified.


lib/http: refactoring Range request, limit content served by server::
+
--
When server receive,

	GET /big
	Range: bytes=0-

and the requested resources is quite larger, where writing all content of
file result in i/o timeout, it is best practice [1][2] if the server
write only partial content and let the client continue with the
subsequent Range request.

In the above case, the server should response with,

	HTTP/1.1 206 Partial content
	Content-Range: bytes 0-<limit>/<size>
	Content-Length: <limit>

Where limit is maximum packet that is reasonable [3] for most of the
client.
In this server we choose 8MB as limit.
--


lib/http: add method Head to Client::
+
The Head method send the HEAD request to path, with optional
headers, and params in query parameters.


lib/ini: add method Keys::
+
The Keys method return sorted list of all section, subsection, and
variables as string where each of them separated by ":", for example
"section:sub:var".


[#v0_52_0]
== pakakeh.go v0.52.0 (2024-01-06)

[#v0_52_0__new_features]
===  New features

ssh/config: add method MarshalText and WriteTo::
+
--
The MarshalText method encode the Section back to ssh_config format
with two spaces as indentation in key.

The WriteTo method marshal the Section into text and write it to
[io.Writer] w.
--

lib/ssh: implement method Output on Client::
+
--
The Output method run the command and return its standard output and
error as is.
Any other error beside standard error, like connection, will be returned
as error.
--

ssh/sftp: implement method MkdirAll on Client::
+
--
The MkdirAll create directory on the server, from left to right.
Each directory is separated by '/', where the left part is the parent of
the right part.
This method is similar to [os.MkdirAll].
--

cmd/httpdfs: implement [libhttp.Server] with [memfs.MemFS]::
+
--
The httpdfs is a program to serve a directory under HTTP.
--

[#v0_52_0__breaking_changes]
=== Breaking changes

ssh/config: refactoring the Config merge::
+
--
This changes rename method [Config.Prepend] to [Config.Merge].

The way that how the other Config merged is changed.
Instead of appending all of other's sections into the current Config,
append the other Config instance to the current instance of Config.

During [Config.Get] the top Config will be evaluated first, and then the
other Config is evaluated in order of Merge.
--

ssh/config: add parameter Config to NewSection::
+
--
This changes how the Section and parser initialized.

Previously, the Config depends on the parser to set the workDir and
homeDir and Section depends on Config only on Get; now its the other
way around, from top to bottom.
Config initialized first, then parser initialized using Config instance,
and then Section initialized also using Config instance.
--

lib/ssh: add parameter context to Execute method::
+
--
This changes require the fork of our golang.org/x/crypto.
--

lib/time: remove UnixMicro and UnixMilli::
+
--
Both of those methods has been added into standard library as
[Time.UnixMicro] and [Time.UnixMilli] since Go 1.17.
--

lib/io: removed, this package has been merged into "lib/os"::
+
--
While some functions are merged to "lib/os", some are not used anymore
like io.Reader.
--

lib/parser: removed, this package has been merged into lib/strings::


[#v0_52_0__bug_fixes]
=== Bug fixes

ssh/config: fix setting the default values::
+
--
The field default value should be set on Get, after all the Host or
Match fields merged.
In this way, if the field key already set, its not overridden by the
default value or subsequent Host or Match value.
--

ssh/config: set the Hostname if its not set on [Config.Get]::
+
--
Per manual ssh_config(5) on Hostname,

[quote]
The default is the name given on the command line.

So, if the requested host name match with one of Host or Match, but
Hostname is not set, it should be default to the requested parameter
name.
--

http/sseclient: fix data race on [Client.Close]::
+
--
The data race happened when Close set conn to nil but the consume
method still on Read.
The fix is by waiting for 100ms so consume goroutine can check if closeq
is triggered from Close or not.
--

http/sseclient: fix Retry value not set to millisecond::
+
--
When client receive "retry:" message, the value is in millisecond, but
when we store it we only convert it to [time.Duration] which default
to nanosecond.

While at it, update comments on field [Client.Retry] and
[Client.Insecure].
--

ssh/sftp: fix Stat on empty remote file name::
+
--
The implementation of SSH server (openssh) for Stat is not consistent with
the RFC.
The RFC mentioned that

[quote]
An empty path name is valid, and it refers to the user's default
directory (usually the user's home directory).

But this only working on some command, like Mkdir, but not Stat.
--

ssh/sftp: fix non-nil returned error on Close::
+
--
This changes fix the Close that always return an error.
--


[#v0_52_0__enhancements]
===  Enhancements

ssh/config: merge the Section slice values on [Section.merge]::
+
--
Instead of using [Section.Set], set the key-value directly.

While at it, merge the certificateFile, IdentityFile, knownHostFiles,
and sendEnv.
--

ssh/config: set the default UserKnownHostsFile in setDefaults::
+
--
While at it, unfold each value of IdentityFile and UserKnownHostsFile
in setDefaults, by expanding "~" into user's home directory or joining
with "config" directory if its relative.
--
