=  CHANGELOG
:toc:

This library is released every month, usually at the first week of month.

==  share v0.25.0 (2021-04-06)

===  Breaking changes

*  all: refactoring the test.Assert and test.AssertBench signature

   Previously, the test.Assert and test.AssertBench functions has the
   boolean parameter to print the stack trace of test in case its not equal.

   Since this parameter is not mandatory and its usually always set to
   "true", we remove them from function signature to simplify the call
   to Assert and AssertBench.

*  all: refactoring http.Client methods signature

   Previously, parameters to method Delete, Get, Post, PostForm, PostFormData,
   PostJSON, Put, and PutJSON are in the following order:

     (headers, path, params)

   This is sometimes confusing. To make it better and works with format
   of HTTP request header,

     METHOD PATH
     HEADERS

     PARAMS

   we move the path to the first parameter and headers as the second
   parameter, so the call to client methods would be

     (path, headers, params)

*  http: remove parameter contentType on Client method Put

   Since one can set the Content-Type in parameter headers, this parameter is
   become redundant.

===  New features

* http: add method to generate standard HTTP request on Client

  The GenerateHttpRequest method generate http.Request instance from
  method, path, requestType, headers, and params.

  For HTTP method GET, CONNECT, DELETE, HEAD, OPTIONS, or TRACE; the params
  value should be nil or url.Values.
  If its url.Values, then the params will be encoded as query parameters.

  For HTTP method is PATCH, POST, or PUT; the params will converted based on
  requestType rules below,

    * If requestType is RequestTypeQuery and params is url.Values it will be
      added as query parameters in the path.

    * If requestType is RequestTypeForm and params is url.Values it will be
      added as URL encoded in the body.

    * If requestType is RequestTypeMultipartForm and params type is
      map[string][]byte, then it will be converted as multipart form in the
      body.

    * If requestType is RequestTypeJSON and params is not nil, the params will
      be encoded as JSON in body.

* ssh: ask for passphrase if private key is encrypted on generateSigners

  In case the private key defined in IdentityFile is encrypted, prompt
  for the passphrase on the screen and read it from stdin using
  terminal.ReadPassword().

  This changes also remove call to generateSigners on postConfig(),
  instead invoke it from NewClient() to minimize multiple calls to
  generateSigners().

* ssh: use the SSH agent to authenticate on NewClient

  Previously, the client use the IdentityFile on ConfigSection to
  Authenticate with the remote SSH server.  In case the IdentityFile is
  Encrypted with passphrase, each time NewClient is invoked it will ask
  For passphrase.
  
  To minimize inputing the passphrase, we check if current use run the
  SSH agent through SSH_AUTH_SOCK environment variable and use the agent
  To generate signers.
  
  This method need manual key added by user to SSH agent before calling
  NewClient to make it works.

===  Enhancements

* xmlrpc: add debug statements to print request and response

  The debug level is set minimum to 3. If its set it will print the
  request and response to standard output.


==  share v0.24.0 (2021-03-06)

===  Breaking changes

*  http: add prefix Header to constants AcceptEncoding and ContentEncoding

   Since both of those constants are used only for HTTP header, it could
   be more clear if we prefix it with "Header".

*  sql: change the parameter ExtractSQLFields to driver name

   Previously, we use the string as parameter to set the returned place
   holders.

   This commit changes the parameter to the driver name so if the value
   is "postgres" the place holders will be returned as counter, for example
   "$1", "$2", and so on.

*  http: rename "GenericResponse" to "EndpointResponse"

   Well, the hard thing in software is naming a thing.  Using the term
   Generic is too generic, so we change it to make it closer with Endpoint.

*  http: refactoring parameters on Callback and CallbackErrorHandler

   Previously, the parameters to Callback has three types:
   the http.ResponseWriter, *http.Request, and []byte for response body.
   Not only the type names are long, there is no information on the
   registered Endpoint on the receiver of Callback.

   This changes wrap the three parameters into single type EndpointRequest
   with addition field Endpoint, which contains the registered Endpoint.

   On the CallbackErrorHandler we also have three parameters, but instead
   of request body we have an error.

   This changes store the error for CallbackErrorHandler inside
   EndpointRequest.Error field.

*  http: move the CORS options to separate struct

===  New features

*  http: add methods IPAddressOfRequest and ParseXForwardedFor

   The IPAddressOfRequest get the client IP address from HTTP request header
   "X-Real-IP" or "X-Forwarded-For" or from Request.RemoteAddr, which ever
   non-empty first.

   The ParseXForwardedFor parse the HTTP header "X-Forwarded-For" value from
   the following format "client, proxy1, proxy2" into client address and
   list of proxy addressess.

*  api/slack: create new client for webhook

   Unlike PostWebhook API which is close and open one connection at the
   time, the WebhookClient is keep open.

   Use the WebhookClient for long running program that post message every
   minutes or seconds.

*  mlog: implement MultiLogger

   MultiLogger represent a single log writer that write to multiple outputs.
   MultiLogger can have zero or more writers for standard output (normal log)
   and zero or more writers for standard error.

   The MultiLogger is buffered to minimize waiting time when writing to
   multiple writers that have different latencies.
   For example, if we have one writer to os.Stdout, one writer to file, and
   one writer to network; the writer to network may take more time to finish
   than to os.Stdout and file, which may slowing down the program if we want
   to wait for all writes to finish.

   For this reason, do not forget to call Flush when your program exit.

   The default MultiLogger use time.RFC3339 as the default time layout, empty
   prefix, os.Stdout for the output writer, and os.Stderr for the error
   writer.

   Format of written log,

     [time] [prefix] <message>

   The time and prefix only printed if its not empty, and the single space is
   added for convenience.
   Unlike standard log package, this package does not add new line to the end
   of message if its not exist.

*  http: export the HandleFS method

   The HandleFS handle the request as resource in the memory file system.
   This method only works if the Server.Memfs is not nil.

   If the request Path exists in file system, it will return 200 OK with the
   header Content-Type set accordingly to the detected file type and the
   response body set to the content of file.
   If the request Method is HEAD, only the header will be sent back to client.

   If the request Path is not exist it will return 404 Not Found.

*  clise: add method Pop

   The Pop method remove the last Push()-ed item and return it to caller.
   It will return nil if no more item inside it.

*  ini: add support for marshaling slice of struct

   Given a struct with exported field is slice of struct and tagged with
   section and sub-section, the exported field will be marshalled as,

     [section "sub"]
     field = value

*  ini: add support for marshaling pointer to struct and to time.Time

   Given the following field struct with tag,

      V *T `ini:"sec:sub"

   If the V is not nil, it will marshal it into,

      [sec "sub"]
      <field name or tag> = <field value>

*  ini: add support for un-marshaling to struct and slice of struct

*  big: add method that implement sql/driver.Valuer for type Rat

   The Rat.Value() return the value as []byte.

=== Enhancements

*  clise: make all methods safe for concurrent use

*  http: add fields for paging on GenericResponse

   If the response is paging, contains more than one item in data, one
   can set the current status of paging in field Offset, Limit, and Count.

   The Offset field contains the start of paging.
   The Limit field contains the maximum number of records per page.
   The Count field contains the total number of records.

=== Bug fixes

*  reflect: check using equal statement on IsNil

   Beside using IsNil(), return the last check using "v == nil".


==  share v0.23.0 (2021-02-05)

This release bring major refactoring to package memfs to allow embedding two
or more directories in single package.

The minimum Go version is increased to 1.14.

===  Breaking changes

*  memfs: refactoring, allow multiple instances of memfs in single package

   Previously, the generated Go code from memfs can be used only once
   on the package that use it.  For example, if we have two instances of
   memfs.MemFS and both of them call GoGenerate(), when we load them back
   again only the last one will be active and set the global variable
   memfs.GeneratedPathNode.

   This changes refactoring on how we use memfs by storing the
   generated path node into variable that is defined by user and pass
   them to New Options.

*  memfs: remove field WithContent

   The field WithContent is not necessary if we set MaxFileSize to negative
   value.

*  http: embed the memfs.Options into ServerOptions

   This is to minimize duplicate on fields names and give clear distinction
   between options for Server and options for serving files on memory using
   memfs.

*  io: embed the memfs.Options into DirWatcher

   This is to minimize duplicate configuration between DirWatcher and
   memfs, and to allow clear distinction between which options that
   affect the directory tree and options for DirWatcher.

*  memfs: allow AddFile to set internal path

   Previously, AddFile set the internal path equal to path of file to be
   included.  This may cause conflict if the file is already included
   due to the same sys path but different internal path.

   This commit add parameter internalPath to set custom internal path in
   the memfs map.

*  memfs: refactoring Go generate code to use memfs.MemFS instance

   Instead of using memfs.PathNode, which is confusing for new user
   (what is PathNode?), we actually can use memfs.MemFS instance.

   This effect on how we use memfs in http package.

*  dns: change the SOA field in ZoneFile to non-pointer

   The reason we use pointer for SOA record is so we can save them only
   if its not nil.  A nil SOA record cause the generated JSON become "null"
   and this is make the consumer of ZoneFile do more work, checking for the
   null and initialize it when required.

   This changes, make the SOA record to non-nil and we save the record only
   if the MName field is not empty.

*  dns: replace master word with zone

   This is for consistency for type and variable names.

*  sql: sort returned names on ExtractSQLFields sorted in ascending

   This is to make sure that any test that use the package always
   predictable.

   While at it, add paramter to change placeholder on ExtractSQLFields.

===  New features

*  http: add method Post on client

   The Post method send the POST request to path without setting
   "Content-Type".

*  lib/clise: new package that implement circular slice

   A circular slice is a slice that have fixed size.
   An append to slice that has reached its length will overwrite and start
   again from index 0.

   For example, a clise with size 5,

     c := clise.New(5)
     c.Push(1, 2, 3, 4, 5)
     fmt.Printf("%v\n", c.Slice()) // [1 2 3 4 5]

   If we push another item, it will overwrite the first index,

     c.Push(6)
     fmt.Printf("%v\n", c.Slice()) // [6 2 3 4 5]

   See the examples for usage of the package.

*  time: add function UnixMicro that return UNIX time in micro seconds

*  api/slack: simple API for sending message to Slack using only
   standard packages.

*  runes: add function to inverse the slice of rune

   The Inverse function reverse the order of slice of rune without
   allocating another slice.

*  big: add method Humanize

   The Humanize method return the r as string with custom thousand and
   decimal separator.

*  big: add method to round fraction to nearest non-zero value

   The RoundNearestFraction does not require precision parameter, like in
   other rounds function, but it figure it out based on the last non-zero
   value from fraction.

===  Enhancements

*  dns: change the error messages on ResourceRecord initAndInitialize

   This change make the error message more readable and understandable by
   consumer

*  dns: add method to get list of non-local caches in the Server

   The CachesLRU method return the list of non-local caches ordered by
   the least recently used.

   This changes affect the answer type which must be exported, including
   most of its fields, so consumer can access it.

===  Bug fixes

*  sql: check nil on Migrate parameter "fs" using reflect.IsNil

   If we pass nil pointer of type to fs, the if condition will not true
   and this cause panic because fs is not nil.

*  http: fix the package documentation

   The RegisterXxx methods on Server has been replaced with single method,
   RegisterEndpoint.

*  dns: fix saving the TXT record file on zone file

   The TXT record value must be wrapped with quote when stored on zone
   file.


==  share v0.22.0 (2021-01-06)

===  Breaking changes

* contact: remove unused package proofn

* sql: change the new client function parameter into struct of options.

===  New features

*  cmd: add new CLI "totp"

   The totp is a program to generate Time-based One-time Password from
   secret key.

*  totp: add method to generate n number of passwords

===  Enhancements

*  http: print client request if debug value is equal or greater than 2.

   If user set DEBUG environment variable or debug.Value to 2 or greater,
   the http Client will print the request (header and body) to the
   standard output.

*  ssh: print the private key file that has an error when generating signers


==  share v0.21.0 (2020-12-06)

===  Breaking changes

*  test: refactoring Assert with better error message

   The new Assert function use the reflect.DoEqual that return an error
   which describe which field have unmatched value.

===  New features

*  http: allow Endpoint to register custom error handler

   The new field ErrorHandler on Endpoint allow the implementor to define
   their own function to handler error from Endpoint.Call.

   If the ErrorHandler is nil it will default to DefaultErrorHandler.

*  totp: new package that implement TOTP protocol

   Package totp implement Time-Based One-Time Password Algorithm based on
   RFC 6238.

===  Bug fixes

*  parser: fix Line method that always return non-empty line

   In case of content end without new line, for example "a\nb", the Line()
   method always return "b, 0" on the last line.

*  smtp: update the expired test certificate

*  websocket: create buffered channel for running queue.

   This is to fix Stop() method waiting for running channel to be consumed.

===  Enhancements

*  big: update the latest expected error message with Go tip

*  http: add an example on how to write custom HTTP status code

   The example show how to use http.ResponseWriter.WriteHeader to write
   custom HTTP status code instead of relying on errors.E.

*  net: always return the host name or IP on ParseIPPort.

   Previously, if the address is an IP address the returned value is empty,
   for example "127.0.0.1" will return empty host but with non-nil IP and
   port.

   This changes always return the host either as host name (the same as
   paremeter) or valid IP address.

===  Chores

*  all: replace the tasks to serve and generate docs using ciigo as library

   This way, one does not need to install ciigo binary, only require Go
   tools.


==  share v0.20.1 (2020-11-08)

===  Bug fixes

* websocket: set TLSConfig to nil if Endpoint scheme is not https or wss
  If user set TLSConfig but the Endpoint is not start with "https" or "wss",
  client open() method may return an error "Connect: tls: first record does
  not look like a TLS handshake".

* paseto: add 5 seconds time drift when validating JSONToken

===  Enhancements

* big: add method RoundToNearestAway and RoundToZero

  RoundToNearestAway round r to n digit precision using nearest away mode,
  where mantissa is accumulated by the last digit after precision.
  For example, using 2 digit precision, 0.555 would become 0.56.

  RoundToZero round r to n digit precision using to zero mode.
  For example, using 2 digit precision, 0.555 would become 0.55.

* parser: add Stop method

  The Stop method return the remaining unparsed content and its last
  position, and then call Close to reset the internal state back to zero.

===  Chores

* paseto: fix linter warnings


==  share v0.20.0 (2020-10-05)

===  New features

*  lib/paseto: a simple, ready to use, implementation of Platform-Agnostic
   SEcurity TOkens

   This implementation only support PASETO Protocol v2.

   This library focus on how to sign and verify data, everything else is
   handled and filled automatically.

===  Enhancements

* dns: serve DoT without SSL if server is behind proxy or tlsConfig is null
  Previously we only check for tlsConfig, if its null the DoT server
  will not running.
  There is a use case where the SSL terminated by proxy and the connection
  is forwarded to DNS server, so this changes accommodated it.

* http: increase the debug level from 2 to 3


==  share v0.19.0 (2020-09-08)

===  Breaking changes

*  dns: unexport the Messsage's Packet field

*  dns: change the HostsFile Messages to list of ResourceRecord

*  dns: unexport the master file path field

*  dns: refactoring the ResourceRecord values from []byte to string

   There are two reasons for this changes.  First, to allow JSON encoded
   of ResourceRecord.Value without encoded to base64.

   Second, to minimize unreleased packet due to the backing storage is
   still used when assigned to Value (or any []byte field in RDataXXX).

*  dns: dns: split between MasterFile and masterParser

   While at it add field Records that contains unpacked ResourceRecord as
   mapping between domain and ResourceRecord.

   This is useful for client that need to edit the RR in MasterFile.

   This changes also unexport the Messages field, to access it use the method
   Messages.

*  websocket: move the server handler to ServerOptions

===  New features

*  dns: add method to remove local caches by names on Server

*  dns: add method to search caches

*  dns: add method Delete to MasterFile

*  dns: add method to remove RR from cache and master file

*  dns: add method to save the master records to file

*  dns: implement method to add new RR to master file

*  dns: add method to update/insert resource record to caches

*  dns: add method to initialize and validate ResourceRecord

*  websocket: add server options to change the connect and status paths

   Previously, there is only one option for server, the port where it will
   listen.

   This changes add option to change the connect path (default to "/"
   previously) and new path and handler for retrieving server status.

===  Bug fixes

*  dns: fix parsing SOA resource record data from master file

*  dns: stop all forwarders on Stop()

*  http: write the HTTP status code after setting content-type on error

*  ini: ignore the last empty line on unsetAll


==  share v0.18.0 (2020-08-06)

===  Breaking changes

*  big: add global flag MarshalJSONAsString

   MarshalJSONAsString define the default return behaviour of MarshalJSON().
   If its true (the default) the returned JSON format will encapsulated in
   double quote, as string instead of as numeric.

*  dns: refactoring resource record fields

*  http: do not return error based on response code

   The error in doRequest should be about connection error, everything
   else should be handled by user.

*  http: allow setting response type when registering PUT

   User of this library may want to return something and they will suprised
   if the library always set the response type to None.

===  Bug fixes

*  http: fix panic if Request.Form is not initialized on Endpoint.call

===  Enhancements

*  dns: add method to create Message from hostname and list of addresses

*  dns: add method to remove caches by names on Server

*  http: add method Put for Client

*  http: add method to convert RequestMethod to string

*  parser: add method to get single line

*  strings: add function to delete a value from slice of string


==  share v0.17.0 (2020-07-05)

===  Breaking changes

*  dns: replace RDataText with plain []byte

*  http: add parameter headers to client methods

*  http: return the http.Response as the first parameter

===  Bug fixes

*  http: initialize TLSClientConfig only if insecure is true

*  io: truncate file on Copy

*  websocket: fix race on pingTicker when stopping server

===  Enhancements

*  http: check for possible index.html file on getFSNode

*  http: add method Delete

*  http: add method Stop for HTTP server

*  http: check the number of bytes written on ResponseWriter.Write

*  http: log error if path not exist if debug value is set to 3 or greater

*  smtp: check for EOF when receiving data from server


==  share v0.16.0 (2020-06-05)

===  Breaking changes

*  dns: refactoring loading hosts and master files

   Instead of as methods in Server, we detach the LoadHostDir and
   LostMasterDir into functions that return list of filename and their
   content.

*  dns: disable serving DoH and DoT if port is not set (0)

   Previously, if HTTPPort or TLSPort is not set (0) we set it to default
   value and keep serving the DNS over HTTP and TLS.  Sometimes, user may
   want to serve DNS over UDP only.

   This changes disable serving DNS over HTTP (DoH) and TLS (DoT) if port
   is not set, or 0.

*  email: rename ParseAddress function to ParseMailboxes

*  http: add parameter "insecure" when creating new client

*  ini: fix inconsistencies between empty string and boolean true

   In Git specification, an empty variable is equal to boolean true.
   This cause inconsistency between empty string and boolean true.

*  memfs: simplify the API, add directory parameter to New

   This changes add parameter directory to be mounted in New(), so user
   did not need to call Mount manually

   This cause the Mount method and its sibling, Unmount and IsMounted
   become unneeded, so we remove them.

===  Bug fixes

*  api/telegram/bot: fix  request parameter on GetMyCommands

===  New features

*  bytes: add function MergeSpaces

   The function MergeSpaces will convert sequences of white space into
   single space ' '.

*  email: add methods to unmarshal/marshal Mailbox from/to JSON
*  email: add function to parse single mailbox
*  email: add function to create multipart text and HTML message

*  http: support CORS with white list of origin and headers

*  ini: add method UnsetAll to remove all variables in section and/or
   subsection that match with the key
*  ini: add method to Unmarshal ini values to struct

*  os/exec: new package to simplify the standard "os/exec"

   New extension to standard package is function ParseCommandArgs() that
   receive input as string and return itas command and list of arguments.
   Unlike strings.Fields() which only separated the field by space,
   ParseCommandArgs can detect possible single, double, or back quotes.

   Another extension is Run() function that accept the string command
   to be executed and their standard output and error.

*  sql: add method to migrate database schema

   The Migrate method migrate the database using list of SQL files inside
   a directory.
   Each SQL file in directory will be executed in alphabetical order based on
   the last state.

   The state of migration will be saved in table "_migration" with the SQL
   file name that has been executed and the timestamp.

===  Enhancements

*  api/telegram/bot: delete webhook upon setting new webhook

*  dns: do not load hidden hosts and master file

   Previously, the LoadHostDir and LoadMasterDir load all files inside
   the directory without checking if its hidden (starting with dot) or not.

   This changes make the hidden file not loaded so one can disable it
   temporarily by prefixing it with dot.

*  ini: make the add method append the variable after existing same key

*  memfs: make the Node Readdir works when calling from generated Go code

   Previously, the Go generated code from call to GoGenerate() set only
   mapping of path to node.  Calling Readdir() using http.File using

     root, err := mfs.Open("/")
     fis, err := root.Readdir(0)

   will return nil on fis.

   This changes add all child nodes to generated node.

*  websocket: allow "https" scheme on Client's Endpoint


==  share v0.15.0 (2020-05-04)

===  Breaking changes

*  big: check for zero length slice of byte or string on toRat
*  ssh: replace the ClientConfig with ConfigSection

===  New features

* ssh: implement SSH client configuration parser -- ssh_config(5)
* api/telegram/bot: Go package for Telegram API Bot
* http: implement a simplified HTTP client
* net/html: new package to simplify the golang.org/x/net/html

  The x/net/html package currently only provide bare raw functionalities
  to iterate tree, there is no check for empty node, no function to
  get attribute by name, and no simple way to iterate tree without looping it
  manually.

  This package extends the package by adding methods to get node's attribute
  by name, get the first non-empty child, get the next non-empty sibling, and
  to iterate each node in the tree from top to bottom.

===  Enhancements

*  big: return "0" instead of "<nil>" on Rat.String()
*  big: return false if Rat is nil on IsGreaterThanZero
*  http: add parameter to set default client's headers
*  websocket: add method to gracefully Close the client connection
*  websocket: add routine that send PING control frame on Connect

===  Bug fixes

*  reflect: remove checking for method IsEqual on type reflect.Ptr


==  share v0.14.0 (2020-04-03)

===  Breaking changes

*  http: simplify server Endpoint registrations

   Previously, each endpoint with method DELETE, GET, PATCH, POST, and PUT
   require calling different call for registration.  This change simplify
   it to one call only, "RegisterEndpoint", and the registration process
   will be handled automatically based on value on field Method.

*  mining/math: move the package from "lib/mining/" to "lib/" directory

===  New features

*  debug: add a wrapper for starting and stopping CPU profile

*  math/big: new package that extends the capabilities of "math/big"

   The "big" package add custom global precision, rounding mode, and number
   of digit precision after decimal point for all instance of Float that
   use the package.

*  reflect: new package that extends the standard reflect

   This package add new interface "Equaler", it is an interface that
   have single method "IsEqual()".

   Also, we have new function "IsNil(interface{})" that will return true
   if the value in interface{} is nil.

*  strings: add function SingleSpace

   The SingleSpace function convert all sequences of white spaces into
   single space ' '.

===  Enhancements

*  http: embed the standard http package instead of separate field

*  hunspell: return the stem instead of root word on Spell() method

*  hunspell: add Stem() method to Spell and Stem

   The Stem() method reduce inflected (or sometimes derived) words to
   their word stem, base, or root form.

*  hunspell: add Analyze() method to Spell and Stem

   The Analyze() method will return list of morphological fields of the
   word.

*  strings: check for other white spaces on MergeSpaces

===  Bug fixes

*  http: fix the content-length header not set if file is not cached


==  share v0.13.0 (2020-03-11)

===  Breaking changes

Set the minimum Go version to 1.13.

===  New features

*  hunspell: a library to parse the Hunspell file format
*  parser: provide a common text parser, using delimiters

===  Enhancements

*  dns: use net.Addr for primary and fallback UDP/tCP addresses
*  dns: change the mark of input/output in log output
*  io: add function to copy file
*  time: add functions to get Unix time in milliseconds (int64 and string)
*  websocket: allow custom TLS configuration on client

===  Bug Fixes

*  dns: fix handling server without fallback forwarder
*  dns: check for nil DNS-over-TLS server on server's Stop


==  share v0.12.0 (2020-02-13)

===  Breaking changes

*  bytes: move function JSONEscape and JSONUnescape to package json
*  strings: move JSONEscape and JSONUnescape to package json
*  time: change the Microsecond return type from int to int64
*  websocket: change the RouteHandler signature to return Response

===  New features

*  json: new packages to work with JSON
*  sql: a new package as an extension to "database/sql"
*  xmlrpc: new package for working with XML-RPC

===  Enhancements

*  strings: add function to reverse a string

===  Bug fixes

*  dns: fix index out of range when unpacking OPT RR


==  share v0.11.0 (2019-12-26)

===  Breaking changes

*  dns: merge Start and Wait into ListenAndServe

===  New features

*  memfs: implement http.FileSystem on MemFS
*  memfs: implement http.File on Node
*  memfs: implement os.FileInfo on Node
*  memfs: implement io.Closer, io.Reader, and io.Seeker on Node

===  Enhancements

*  dns: allocate raw packet on receive
*  dns: log the number of pruned records
*  errors: add field Name and err

===  Bug fixes

*  dns: split between read and write timeout for TCPClient


==  share v0.10.2 (2019-12-07)

===  Bug Fixes

*  dns: check for bad certificate when reading DoT request
*  dns: fix the use of goroutine on runForwarders


==  share v0.10.1 (2019-12-05)

===  Bug Fixes

*  dns: close the connection if receiving zero packet on serveTCPClient
*  dns: increase and decrease number of forwarders only for primary forwarders
*  dns: make the stopper channel to be buffered
*  dns: check for nil forwarder
*  dns: check for nil connection on DoTClient's Close
*  dns: check for zero query type and class on TCPClient Lookup method
*  dns: check for nil connection on Close at TCPClient
*  dns: minimize double looping on checking error at serveTCPClient
*  git: fix the test using full path URL and repository directory
*  io: fix test using existing file instead of generate file
*  net: handle interrupted system call on epoll Wait
*  ssh: fix test ClientConfig initialize on Github Actions
*  websocket: remove test for empty endpoint due to different format
*  websocket: fix zero response ID when error on handleText

===  Enhancements

*  dns: remove the use of pointer on Message fields
*  dns: remove the use of ResourceRecord pool
*  http: add method HTTPMethod to Endpoint
*  http: disable creating Memfs if Root options is empty
*  memfs: remove unneeded call to GeneratedPathNode.Set
*  mining: move commands to root
*  websocket: add examples of WebSocket as chat server and client
*  websocket: add new function to create broadcast response
*  websocket: add field Conn to represent connection in Request
*  websocket: check for read timeout on recv
*  websocket: remove unused error on NewServer

==  share v0.10.0 (2019-11-05)

===  New Features

*  dns: implement client and server for DNS over TLS
*  ini: add method GetsUniq and ValsUniq that return uniq values only
*  net: implement network polling using epoll and kqueue

===  Breaking Changes

*  dns: change the server certificate options to load from files
*  ini: change Gets return as is, with duplicate values

===  Enhancements

*  dns: allow listening on DoH without requiring certificate
*  ini: support marshaling and un-marshaling time.Duration
*  ini: support marshaling and un-marshaling time.Time
*  ini: support marshaling and un-marshaling embedded structs
*  websocket: websocket: replace epoll implementation with libnet.Poll

===  Bug Fixes

*  dns: return error code 4 if server receive unknown message class or type
*  dns: return an error if section question contains invalid packet
*  ini: fix return value for empty string in IsValueBoolTrue
*  strings: fix logic of Split function
*  websocket: set the response ID after calling handler on handleText
*  websocket: wrap the response with frame on sendResponse


==  share v0.9.0 (2019-10-08)

===  New Features

*  bytes: add function to get all indexes of word in string
*  bytes: add function to take snippets from string by indexes
*  bytes: add function to get all indexes of token in string
*  ints: add function to merge two slices by distance
*  memfs: add method to add file directly as child of root
*  memfs: add method to Search content of files
*  sanitize: new package to sanitize markup document into plain text
+
Current implementation have a function to sanitize the content of HTML.

*  strings: add function to convert slice of string to slice of slice of bytes

*  http: implement key binding in registered Endpoint's Path
+
Previously, only raw path can be registered on Endpoint.  This changes
implement key binding using colon ":" on path.  For example, registering
path "/:x/y" will bind key "x" to a string value that can be accessed on
http.Request.Form using Get method.

===  Breaking Changes

*  ini: set variable with "=" without a value default to empty string

Previously, a variable end with "=" will have value set to "true".
For example,

----
[section]
var =
----

set the "var" value to string "true".

This changes make the variable that end with "=" without any value
to be an empty string, so "var" value is equal to "".

===  Bug Fixes

*  ini: check for possible nil variable on Write

*  dns: allow message with non recursive-desired to be forwarded
+
On macOS, turn out, all DNS queries have RD flag set to zero.  This cause
no DNS queries forwarded to parent server.

===  Enhancements

*  http: export the Memfs field on Server
+
User of HTTP can use the Memfs field to get the content manually or
to Search the content.

*  http: add content and response type HTML and XML

*  memfs: export the Decode method on Node


==  share v0.8.2 (2019-09-05)

===  Enhancements

*  http: make the request body always available even after ParseForm()
+
Previously, if the request type is query, form, or JSON, we call the
ParseForm() to let the http.Request read the Body POST form data and fill
the Form and/or PostForm fields.  This  method will cause the request
Body will become empty since its already read and closed.
One of use case of POST with form data is to check the integrity of POST
body using checksum, which is not possible using only ParseForm().
This commit read all the body first into reqBody and recreate the request
Body back using ioutil.NopCloser and bytes.Buffer.

*  all: replace document generator from asciidoctor to ciigo
+
Previously, generating HTML files from asciidoc files require installing
ruby, asciidoctor, and its dependency through Gemfile.
To simplify this, we replace it with ciigo.  Ciigo not only can convert
the asciidoc files but it also support serving the file inside HTTP
server and watching changes on asciidoc files during development for
local previewing.

*  memfs: log and ignore error from NewNode
+
An error for calling NewNode should not stop processing all files
in directory.

*  io: log and ignore error from NewNode
+
An error for calling NewNode should not stop processing all files
in directory.


==  share v0.8.1 (2019-08-05)

===  Enhancements

*  lib/ini: add functions to marshal/unmarshal bytes from/to struct.
+
The format to marshal/unmarshal ini stream is behave like JSON.

*  lib/memfs: add method to encode the content of file.
+
The ContentEncode() method encode each node's content into specific
encoding, in other words this method can be used to compress the content
of file in memory before being served or written.
Only file with size greater than 0 will be encoded.
List of known encoding is "gzip".

*  lib/memfs: ignore generated output filename on GoGenerate
+
In case the user Mount() the directory that include the generated output
file, we want that file to be excluded from .go static source.

*  lib/memfs: set the Node Size to be zero if node is directory


==  share v0.8.0 (2019-07-09)

===  Breaking changes

*  All ASCII related contants and functions now being moved from `bytes`
   package to `ascii` package.

===  New Features

*  ascii: new library for working with ASCII characters

===  Enhancements

*  dns: add method to restart forwarders
*  dns: add fallback nameservers
*  ini: create new section or variable if not exist on Set


==  share v0.7.0 (2019-06-14)

This release bring major refactoring on `ini` package to provide a clean and
simple API.

===  Breaking Changes

*  ini: major refactoring
*  net: add parameter to check Fully Qualified Domain Name on IsHostnameValid

===  New Features

*  spf: implementation of Sender Policy Framework (RFC 7208)
*  ssh: package ssh provide a wrapper to golang.org/x/crypto/ssh

===  Enhancements

*  dns: add function to lookup PTR record by IP address
*  dns: export Lookup method as part of Client interface
*  doc: regenerate to use new style
*  http: print the not-found path on Server's getFSNode()
*  ini: add method Vars that return all variables as map
*  ini: add method to Rebase other INI object
*  ini: add method to add, set, and unset variable
*  ini: add method to convert key-value to map
*  ini: add method to get section object by section and/or subsection name
*  ini: add method to get variable values as slice of string
*  ini: add method to prune INI variables
*  ini: add methods to support templating
*  io: add function to check if content of file is binary
*  net: add function to check if IP address is IPv4 or IPv6
*  net: add function to convert IPv6 into dot format
*  ns: set log flag to 0, without time prefix
*  strings: add function to append uniq values to slice of strings

===  Bug Fixes

*  io: watch changes on sub of sub directories on DirWatcher
*  dns: substract the message TTL when the answer found on cache
*  dns: always return true when answers RR exist and no TTL is zero


==  share v0.6.1 (2019-05-11)

*  `memfs`:
**  fix empty list names from MemFS created from GeneratedPathNode
**  set root if GeneratedPathNode is not empty
**  sort the generated file names
**  fix template when generating empty content


==  share v0.6.0 (2019-05-07)

This release bring major changes on dns package.
Most notable changes are adding caches and query forwarding (recursion), and
removing the server handler.


===  Breaking Changes

*  `dns`:
**  refactor server to use Start(), Wait(), and Stop()
**  use direct certificate instance on ServerOptions
**  rename Send to Write, and change the parameter type to slice of byte
**  remove "elapsed" parameter on Message.IsExpired()
**  unexport the Request type
**  remove receiver interface
**  unexport connection type
**  remove unused address parameter on client's Query()
**  unexport all fields from UDP and TCP clients
**  remove TCPPort on ServerOptions

*  `http`:
**  change server initialization using options

*  `io`:
**  simplify Watcher to use callback instead of channel

*  `memfs`:
**  refactoring go generate file to use type from memfs

===  New Features

*  `crypto`: new package that provide a wrapper for standard crypto library

*  `dns`:
**  add caches to server
**  add method to set AA, Query, RD, RCode on Message
**  add mapping of response code to human readable names
**  implement recursion, forwarding request to parent name servers
**  check for zero TTL on authorities and additionals RR on IsExpired

*  `io`:
**  implement naive directory change notification, DirWatcher

*  `memfs`:
**  add parameter to make reading file content become optional
**  add method to unmount directory
**  add method to check if memfs contains mounted directory
**  add method to update node content and information
**  export the method to add new child
**  add method to remove child from any node

*  `smtp`: add field DKIMOptions to Domain

===  Bug Fixes

*  `dns`:
**  fix data race issue when running test
**  set the TTL offset when packing resource record
**  fix parsing TXT from zone file

*  `http`:
**  allow serving directory with slash

*  `memfs`:
**  fix possible invalid system path on file with symbolic link
**  refresh the directory tree in Development mode if page not found

===  Documentation

*  add documentation for Sender Policy Framework (RFC 7208)


==  share v0.5.0 (2019-04-02)

This minor release is dedicated for websocket package.  Major refactoring on
server and client API to make it easy and extensible.  The websocket is now
100% pass the autobahn testsuite (minus compression feature).

===  New Features

*  `cmd/smtpcli`: command line interface to SMTP client protocol
*  `ints`: new package for working with slice of integer
*  `ints64`: new package for working with slice of 64 bit integer
*  `floats64`: new package for working with slice of 64 bit float

===  Enhancements

*  `bytes`:
**  change the Copy return type to non pointer
**  add function to concat slice of byte or string into []byte

*  `ints`: add function to remove value from slice

*  `websockets`:
**  Rewrite most of client and server APIs to be more simple and pass autobahn
    testsuite
**  Minimize global variables and unexport internal constants and functions
**  Handle interjected PING control frame from server
**  Generate random mask only if masked field is set


==  share v0.4.0 (2019-03-01)

===  New Features

*  `email`: new package for working with Internet Message Format (RFC 5322)
*  `email/dkim`: new package for parsing and creating DKIM signature
   (RFC 6376)
*  `email/maildir`: new package to manage email using maildir format

===  Enhancements

*  `bytes`
**  add function to copy slice
**  add function to convert hexadecimal into byte

*  `dns`
**  add mapping of connection types and its names
**  print the section question type by string
**  add method to filter Message.Answer by specific query type
**  add pool for UDP client
**  add function to get list of system name servers
**  make UDPClient Query routine safe
**  increase the internal debug level from 2 to 3

*  `http`
**  add the charset type to content-type "text/plain"
**  listen and serve using TLS if TLSConfig is defined
**  add method to temporary redirect request to other location

*  `ini`
**  unexport the reader
**  add method to get all variable values with the same key

*  `io`
**  rename Reader SkipSpace to SkipSpaces
**  refactoring, export all fields for easy access on Reader
**  add method read one line with line feed
**  add method to unread N characters on Reader
**  optimize ReadUntil without append
**  add method to return the rest of unreaded buffer on Reader
**  return the character separator that found on SkipUntil

*  `memfs`
**  add method to dump files as Go generated source
**  add variable for allowing bypass file in memory

*  `smtp` (work in progress)
**  rename StorageFile to LocalStorage
**  implement server with local handler
**  add prefix Mail to methods in Storage interface
**  use different port between normal listener and TLS listener

*  `time`:  add function to get micro seconds

===  Fixes

*  all: fix the usage of "iota"
*  `dns`: fix creating new UDP/TCP client without port number
*  `memfs`: check for empty directory on Mount


==  share v0.3.0 (2019-02-01)

===  Features Changes

*  `lib/debug`: add function to write heap profile to file
*  `lib/debug`: add type to store relative and difference on memory heap
*  `lib/dns`: remove request pool
*  `lib/dns`: export the connection field on UDPClient
*  `lib/dns`: add type of connection
*  `lib/http`: add parameter http.ResponseWriter to Callback.
*  `lib/http`: the RegisterXxx functions now use the Endpoint type.

===  Enhancements

*  Various fixes suggested by linters
*  doc: add four summary and notes about DKIM
*  doc: add summary of Simple Authentication and Security Layer (SASL)
*  doc: add summary on SMTP over TLS (RFC3207)
*  doc: add notes for Internet Message Format (RFC 5322)
*  doc: add documentation for SMTP and DSN

===  Fixes

*  `lib/git`: fix testdata and test input


==  share v0.2.0 (2019-01-02)

===  New Features

*  `lib/errors`, package errors provide a custom error with code.

*  `lib/http`, package http implement custom HTTP server with memory file
system and simplified routing handler.

===  Enhancements

Fix warnings from linters.


==  share v0.1.0 (2018-11-29)

The first release of `share` package contains one command line interface (CLI)
and several libraries.

The CLI is `gofmtcomment` to convert comment from `+/**/+` to `//`.

The libraries are `bytes`, `contact`, `dns`, `dsv`, `ini`, `io`, `memfs`,
`mining`, `net`, `numbers`, `runes`, `strings`, `tabula`, `test`, `text`,
`time`, and `websocket`.

Documentation for each package can be viewed at,

	https://godoc.org/github.com/shuLhan/share

I hope it will be stay alive!
